remote-theme: jekyll/minima

theme: jekyll-theme-minimal

title: Nima Azbijari
logo: IMG_1481.jpeg

description: I am a graduated CS MSc student looking for work in machine learning. My work in graduate school focused on interpreting deep neural networks that are trained on genomic data. I have also worked on a variety of different projects ranging from speeding up graph computations for social network analysis to building deep learning models to classify cancer from DNA. This website is meant to be a location for writing about my research and other projects.
