remote-theme: jekyll/minima

theme: jekyll-theme-minimal

title: Nima Azbijari
logo: IMG_1481.jpeg

description: I am a PhD student at Oregon State University studying Artificial Intelligence. I have worked on a variety of different projects ranging from speeding up graph computations for social network analysis to building deep learning models to classify cancer from DNA. This website is meant to be a location for writing about my research and other projects.
